### ISSUE TITLE
[1.15.2] Hard Crash - Using only DefaultAmplified-1.15.2-1.3.1.jar

### ISSUE THREAD

**Issue by realTIMematrix** [FoundSpore/DefaultAmplfiedBiomes#4]
[27Jan2020 01:52:51.612] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, realTIMematrix, --version, 1.15.2-forge-31.0.1, --gameDir, C:\Users\Andreas\Documents\Minecraft\Modpacks\1.15.2\Transformation, --assetsDir, C:\Users\Andreas\AppData\Roaming\.minecraft\assets, --assetIndex, 1.15, --uuid, f0b1f77e8d7d40b9a84534986e0a0ea1, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.0.1, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323]
[27Jan2020 01:52:51.614] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_241 by Oracle Corporation
[27Jan2020 01:52:51.976] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[27Jan2020 01:52:52.116] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.net.MalformedURLException: no protocol: 
[27Jan2020 01:52:52.116] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.StringUtils.toURL(StringUtils.java:51)
[27Jan2020 01:52:52.116] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.Optional.map(Unknown Source)
[27Jan2020 01:52:52.116] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:90)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:70)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[27Jan2020 01:52:52.117] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[27Jan2020 01:52:52.118] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[27Jan2020 01:52:52.118] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:70)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.loadModFile(ModFileParser.java:59)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:51)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFile.identifyMods(ModFile.java:132)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:116)
[27Jan2020 01:52:52.119] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:208)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:105)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[27Jan2020 01:52:52.120] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[27Jan2020 01:52:52.126] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[27Jan2020 01:52:52.126] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[27Jan2020 01:52:52.126] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[27Jan2020 01:52:52.127] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[27Jan2020 01:52:52.127] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[27Jan2020 01:52:52.127] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[27Jan2020 01:52:52.127] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[27Jan2020 01:52:52.128] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[27Jan2020 01:52:52.128] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.net.MalformedURLException: no protocol: 
[27Jan2020 01:52:52.128] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URL.<init>(Unknown Source)
[27Jan2020 01:52:52.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URL.<init>(Unknown Source)
[27Jan2020 01:52:52.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URL.<init>(Unknown Source)
[27Jan2020 01:52:52.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.StringUtils.toURL(StringUtils.java:47)
[27Jan2020 01:52:52.131] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 30 more #3

**Comment by FoundSpore** [comment]
Im trying to figure this out
 bare with me

**Comment by FoundSpore** [comment]
Alright it was the dumb update json url. I had to delete the entire line lol

**Comment by realTIMematrix** [comment]
Now it works, thank you :-)
